### ISSUE TITLE
Does `TestItems` need to be a dependency?

### ISSUE THREAD

**Issue by avik-pal** [MilesCranmer/DispatchDoctor.jl#45]
It seems like it isn't being used in `src` https://github.com/search?q=repo%3AMilesCranmer%2FDispatchDoctor.jl+testitem+path%3A%2F%5Esrc%5C%2F%2F&type=code.

It probably doesn't matter too much since it is extremely lightweight.

**Comment by MilesCranmer** [comment]
Good point, I should delete it. Originally there were some `@testitem` throughout the codebase (which TestItemRunner will run automatically – makes TDD-like work significantly faster to have tests) but I moved to `test/` because it is easily-confused with source code (https://github.com/julia-vscode/TestItemRunner.jl/issues/70)
